server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:1234}
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

outbound:
  identity:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "XLbYHipJnfjsjuzsucqFY9wrUAZQGOu+4CLUudIPXKjXt6kOTZX4/mVqo4XxMm0j"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in seconds